version: '3.7'
services:
  gateway:
    build:
      context: ../../
      dockerfile: src/ApiGateway/Dockerfile
    container_name: einventory-gateway
    # restart: unless-stopped
    ports:
      - ${GATEWAY_PORT}:80
    networks:
      - einventory

  catalogs:
    image: catalogs:${TAG}
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Catalogs/Dockerfile
    container_name: einventory-catalogs
    # restart: unless-stopped
    ports:
      - ${CATALOGS_SVC_PORT}:80
    env_file:
      - ../../.docker-envs/catalogs.env
    networks:
      - einventory

  identity:
    image: identity:${TAG}
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Identity/Dockerfile
    container_name: einventory-identity
    # restart: unless-stopped
    ports:
      - ${IDENTITY_SVC_PORT}:80
    networks:
      - einventory

  customers:
    image: customers:${TAG}
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Customers/Dockerfile
    container_name: einventory-customers
    # restart: unless-stopped
    ports:
      - ${CUSTOMERS_SVC_PORT}:80
    networks:
      - einventory

# https://docs.docker.com/compose/networking/
# https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects
networks:
  einventory:
    name: einventory-network
    external: true